name: Tests

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run Tests
    strategy:
      matrix:
        node: [12.x, 14.x, 15.x, 16.x]
        tailwindcss: [1.9, 2.2]
    env:
      TAILWINDCSS_VERSION: ${{ matrix.tailwindcss }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install npm dependencies
        run: npm ci

      - name: Lint code
        if: ${{ matrix.node == '16.x' }}
        run: npm run lint

      - name: Run tests
        run: npm run test
